github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/google-stackdriver","gcr.io/paketo-buildpacks/google-stackdriver"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- id:   google-stackdriver-debugger-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:       cdbg_java_agent_gce\.tar\.gz
    owner:      GoogleCloudPlatform
    repository: cloud-debug-java
    token:      ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- id:   google-stackdriver-debugger-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package: "@google-cloud/debug-agent"
- id:   google-stackdriver-profiler-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/google-stackdriver-profiler-dependency:main
- id:   google-stackdriver-profiler-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package: "@google-cloud/profiler"
